### PR TITLE
add depenpencies check in readme

### PR DESCRIPTION
**Pull request by asmodehn**
Adding mentions of dependencies to check (and maybe install) before trying to compile, in the readme.

### CODE REVIEW

**Comment by asmodehn** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by asmodehn** [comment]
recheck

**Review by rkuhn — APPROVED** [review]
recheck

**Comment by rkuhn** [comment]
Thanks a lot @asmodehn!

**Comment by rkuhn** [comment]
The failure is due to a missing secret (we’ve been working on CI recently), will fix later today and the merge.

**Pull request merged**
